{% set name = "kagglehub" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kagglehub-{{ version }}.tar.gz
  sha256: 5d20a3b9aa851ca56dd09c57bb6d790cbe331e3e4d4c86e8a16575c9400071b6

build:
  script:  {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  skip: True  # [py<38]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - requests
    - tqdm
    - packaging

test:
  imports:
    - kagglehub
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kaggle/kagglehub
  description: |
    KaggleHub is a Python package that provides a simple API to access Kaggle resources anywhere.
  summary: Access Kaggle resources anywhere
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/Kaggle/kagglehub
  doc_url: https://github.com/Kaggle/kagglehub/blob/main/README.md

extra:
  recipe-maintainers:
    - ngam
